# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcreator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
