# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcreator', '0002_auto_20170531_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
    ]
